### ISSUE TITLE
Write basic SQL queries

### ISSUE THREAD

**Issue by m0xb** [CommandAndTriumph/exercises#1]
Run the following SQL to define an entity, `employee`, and create some employees to start with.

```
create table employee (
  name text,
  age int, -- years
  department text,
  hire_date text,
  paygrade text,
  salary int -- annual, in dollars
);

insert into employee 
  (name, age, department, hire_date, paygrade, salary) 
values 
  ('Bob Smith', 53, 'administration', '2017-01-20', 'GS-4', 25514), 
  ('Alice Jones', 27, 'it', '2014-07-13', 'GS-8', 39159),
  ('Frank Brown', 32, 'management', '2010-08-10', 'GS-13', 74584),
  ('Ted Williams', 22, 'it', '2015-12-13', 'GS-4', 25514)
;
```

Then:

1. Write a `SELECT` query to return the number of employees.
2. Write an `INSERT` query to insert a new employee. 
3. Write a `SELECT` query to return the employees ordered by the date they were hired. Hint: use `ORDER BY`.

**Comment by WorryingWonton** [comment]
1:  select count(*) from employee;
2: insert into employee values ('Alan Campbell', 32, 'it', '2013-12-20', 'GS-12', 59159)
3: select select * from employee order by hire_date asc;
4: delete from employee where name = 'Alan Campbell' ;
5: update employee set termination_date = '2017-07-11' where name = 'Bob Smith' and age = 53;
